// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(grunt) {
    var fs, path, _;
    path = require('path');
    fs = require('fs');
    _ = require('lodash');
    return grunt.registerTask('finalia-sitemap', function() {
      var lastModified, sitemapPath, xmlStr;
      lastModified = new Date().toISOString();
      xmlStr = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n   <sitemapindex xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n   <sitemap>\n      <loc>http://www.finalia.pl/sitemap-home.xml</loc>\n      <lastmod>" + lastModified + "</lastmod>\n   </sitemap>\n   <sitemap>\n      <loc>http://www.finalia.pl/blog/sitemap.xml</loc>\n      <lastmod>" + lastModified + "</lastmod>\n   </sitemap>\n</sitemapindex>\n";
      sitemapPath = './dist/sitemap.xml';
      grunt.file.write(sitemapPath, xmlStr);
      grunt.log.writeln('Sitemap created successfully');
      grunt.log.writeln('OK');
      if (grunt.task.current.errorCount) {
        return false;
      } else {
        return true;
      }
    });
  };

}).call(this);
