// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(grunt) {
    var fs, path, _;
    path = require('path');
    fs = require('fs');
    _ = require('lodash');
    return grunt.registerTask('finalia-sitemap', function() {
      var lastModified, sitemapIndexPath, sitemapIndexXmlStr, sitemapPath, sitemapXmlStr;
      lastModified = new Date().toISOString();
      sitemapIndexXmlStr = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n   <sitemapindex xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n   <sitemap>\n      <loc>http://www.finalia.pl/sitemap-home.xml</loc>\n      <lastmod>" + lastModified + "</lastmod>\n   </sitemap>\n   <sitemap>\n      <loc>http://www.finalia.pl/blog/sitemap.xml</loc>\n      <lastmod>" + lastModified + "</lastmod>\n   </sitemap>\n</sitemapindex>\n";
      sitemapIndexPath = './dist/sitemap.xml';
      grunt.file.write(sitemapIndexPath, sitemapIndexXmlStr);
      grunt.log.writeln('Sitemap index created successfully');
      sitemapXmlStr = "<urlset xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd\" xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n  <url>\n    <loc>http://www.finalia.pl/</loc>\n	<lastmod>" + lastModified + "</lastmod>\n	<changefreq>daily</changefreq>\n	<priority>1.0</priority>\n  </url>\n</urlset>\n";
      sitemapPath = './dist/sitemap-home.xml';
      grunt.file.write(sitemapPath, sitemapXmlStr);
      grunt.log.writeln('Sitemap created successfully');
      grunt.log.writeln('OK');
      console.log("I am here!");
      if (grunt.task.current.errorCount) {
        return false;
      } else {
        return true;
      }
    });
  };

}).call(this);
